### PR TITLE
User model

### LINKED ISSUE #15: heroku down?
as of now (march 9th, 3pm), heroku app is down or not deployed. Or the link given in milestone 1 was incorrect.
snapshot1

### PR DESCRIPTION
**Pull request by ZachDFK**
can someone check it out, especially the migrate file(s) for users

### CODE REVIEW

File: db/migrate/20160303155656_create_users.rb [hunk 1]
```diff
@@ -0,0 +1,12 @@
+class CreateUsers < ActiveRecord::Migration
+  def change
+    create_table :users do |t|
+      t.string :username
+      t.string :password
+      t.string :email
+      t.integer :upVote
+      t.integer :downVote
```
Comment (kevincox) [inline db/migrate/20160303155656_create_users.rb]: What are these attributes for?

**Comment by kevincox** [comment]
Can you make all of the fields non-nullable unless you have a good reason not to?

**Comment by ZachDFK** [comment]
Sure. 
Is there a place where I should make comments of what the attributes are supposed to do/represent?

**Comment by kevincox** [comment]
I would put them inside the (currently empty) user model.

File: db/migrate/20160303155656_create_users.rb [hunk 2]
```diff
@@ -0,0 +1,12 @@
+class CreateUsers < ActiveRecord::Migration
+  def change
+    create_table :users do |t|
+      t.string :username null: false 
+      t.string :password null: false
+      t.string :email null: false
+      t.integer :upVote nullL:false default:0
+      t.integer :downVote null:false default:1
```
Comment (kevincox) [inline db/migrate/20160303155656_create_users.rb]: Still why are these here?

Comment (ZachDFK) [inline db/migrate/20160303155656_create_users.rb]: Yeah I prematurely made a commit and I ran into some syntax errors.
but I'm a little confused do you just want to get rid of the migrate file entirely and we just put the schema up  ?

Comment (kevincox) [inline db/migrate/20160303155656_create_users.rb]: No, I'm just referring to the upvote and downvote fields, I don't get their purpose.

Comment (ZachDFK) [inline db/migrate/20160303155656_create_users.rb]: Oh, they are used to calculate the user's 'trust score'. I recall that it was one of the requirements needed.

Comment (ZachDFK) [inline db/migrate/20160303155656_create_users.rb]: I'll remove them I though of something that could work better to find a 'trust score'

Comment (kevincox) [inline db/migrate/20160303155656_create_users.rb]: I suspect it will be easier for now just to do a count on their upvotes. Or the upvotes of their contributions.

**Comment by ZachDFK** [comment]
can I get a :+1:  ?

**Comment by kevincox** [comment]
LGTM :boat:
